sudo: required

services:
  - docker

before_install:
  - docker build -t smalltides/docker-react -f Dockerfile.dev .

script:
  - docker run smalltides/docker-react npm run test -- --coverage 

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-408772917132"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"